version = "Two"

use_field_init_shorthand = true
use_small_heuristics = "Max"
fn_args_layout = "Compressed"

format_code_in_doc_comments = true
wrap_comments = true

reorder_impl_items = true

unstable_features = true
merge_imports = true
